### PR TITLE
Composer, Markdown and readmore notice

### PR DESCRIPTION
**Pull request by rasmustaarnby**
- Added composer file
- Added a markdown version of  the README for better layout on Github
- Fixed PHP notice caused by missing `$readmore` variable when using tooltips.

### CODE REVIEW

**Comment by Mte90** [comment]
The readme.txt is required for the wordpress.org repo so we cannot remove that.

**Comment by rasmustaarnby** [comment]
@Mte90 I haven't deleted the readme.txt but added the markdown version. I understand if you think it seems a little overkill to have to almost identical files in there.

**Comment by Mte90** [comment]
My fault but is useless have two different files for the readme and we cannot approve that.

**Comment by rasmustaarnby** [comment]
Fair enough. This is how others regularly do and what I myself, so I just did this on autopilot.

**Comment by rasmustaarnby** [comment]
@Mte90 I have updated the pull request and deleted the README.md file

**Comment by Mte90** [comment]
Now is perfect!
You can try to merge all the commits in an unique: `git reset --soft HEAD~$1 && git commit;`.
Replace $1 with the numbers of your commits, with that all the commits are merged :-)

**Comment by Mte90** [comment]
I forgotten if you have a wordpress.org profile add your nick in the fields in the readme as contributors :-)

**Comment by Mte90** [comment]
we are working on a minor release and we want your pr for that version :-)

**Comment by rasmustaarnby** [comment]
Sounds good :)

**Comment by Mte90** [comment]
Do you have a WordPress.org profile for the readme?

**Comment by rasmustaarnby** [comment]
Didn't see your comment till now. I'll add it next time, if I send another pull request. :) Thanks.

**Comment by EugenioPetulla** [comment]
@rasmustaarnby don't worry. Write us an email within your wordpress.org username and we will add it to readme. support@codeat.co
:+1:

**Pull request merged**
